### ISSUE TITLE
vbase.ch need :-)

### ISSUE THREAD

**Issue by dannythevii** [hbmshell/core#1]
good morning
thanks for your great work!

in the hbmsamples is missing vbase.ch (need for compile )
also.. where you take the wonderful hbmdialog and others Interpreters  ?  had you made? complements !!
is possible to public the sources?

again thanks again and complements
Daniele

**Comment by hbmshell** [comment]
Hi

Try with --virtual-include parameter in command LINE

hbmdialog main.prg --virtual-include

Best regards


Em dom, 23 de abr de 2023 03:30, dannythevii ***@***.***>
escreveu:

**Comment by hbmshell** [comment]
If you want to see the contents of the files use the --debug-hbm parameter

hbmdialog main.prg --virtual-include --debug-hbm

View the comp.log file
